#!/bin/bash
if [ "$EUID" -ne 0 ]; then
    echo "Must be run as root."
    exit 1
fi
TARGET_SESSION="$1"
TARGET_USER="$2"

mkdir -p /etc/sddm.conf.d
rm -f /etc/sddm.conf.d/autologin.conf

cat > /etc/sddm.conf.d/zz-steamos-autologin.conf << CONFEOF
[Autologin]
User=${TARGET_USER}
Session=${TARGET_SESSION}
Relogin=true
CONFEOF
